{
 "title": "PV",
 "time": { "from": "now-3d", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Übersicht", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT\r\n\t`time`,\r\n\t`Akku SOC`,\r\n\tCASE WHEN `Generator` IS NULL THEN NULL WHEN `Generator` > 0 THEN `Generator` ELSE 0 END AS `Gen Produktion`,\r\n\tCASE WHEN `Generator` IS NULL THEN NULL WHEN `Generator` < 0 THEN `Generator` ELSE 0 END AS `Gen Verbrauch`,\r\n\t`PV Carport`,\r\n\t`PV Dach`,\r\n\tCASE WHEN `Generator` IS NULL THEN NULL WHEN `Generator` > 0 THEN `Generator` ELSE 0 END + `PV Carport` + `PV Dach` AS `PV`,\r\n\t`Verbrauch`,\r\n\tCASE WHEN `Akku` IS NULL THEN NULL WHEN `Akku` < 0 THEN -`Akku` ELSE 0 END AS `Akku laden`,\r\n\tCASE WHEN `Akku` IS NULL THEN NULL WHEN `Akku` > 0 THEN `Akku` ELSE 0 END AS `Akku entladen`,\r\n\tCASE WHEN `Netz` IS NULL THEN NULL WHEN `Netz` < 0 THEN -`Netz` ELSE 0 END AS `Einspeisung`,\r\n\tCASE WHEN `Netz` IS NULL THEN NULL WHEN `Netz` > 0 THEN `Netz` ELSE 0 END AS `Netzbezug`\r\nFROM\r\n\t(SELECT\r\n\t  ROUND(ROUND(UNIX_TIMESTAMP(`timestamp`) * 1000 / $__interval_ms) * $__interval_ms) AS `time`,\r\n\t  AVG(gen_P) AS `Generator`,\r\n\t  AVG(carport_P) AS `PV Carport`,\r\n\t  AVG(roof_P) AS `PV Dach`,\r\n\t  AVG(`battery_P`) AS `Akku`,\r\n\t  AVG(`grid_P`) AS `Netz`,\r\n\t  AVG(`load_total_P`) AS `Verbrauch`,\r\n\t  AVG(`battery_SOC`) AS `Akku SOC`\r\n\tFROM\r\n\t  log.pv\r\n\tWHERE\r\n\t  $__timeFilter(timestamp)\r\n\tGROUP BY\r\n\t\t`time`\r\n\tORDER BY\r\n\t  `time` DESC) AS `t`"
    }
   ]
  },
  {
   "title": "Produktion",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT gen_P+carport_P+roof_P AS `val` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 } },
  {
   "title": "Verbrauch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT load_total_P AS `load_total_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Akku",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT battery_P AS `battery_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Akku",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT battery_V*0.01 AS `battery_V` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 60*12 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Akku",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT `battery_SOC` AS `battery_SOC` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 60*12 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Netz",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT grid_P AS `grid_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Inverter AC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_P AS `inverter_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Backup",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT backup_P AS `backup_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 9, "x": 15, "y": 13 } },
  {
   "title": "Dach",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT roof_P AS `roof_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Carport",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT carport_P AS `carport_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Generator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT gen_P AS `gen_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ROUND(\r\n    ROUND(\r\n      UNIX_TIMESTAMP(`timestamp`) * 1000 / $__interval_ms\r\n    ) * $__interval_ms\r\n  ) AS `time`,\r\n  (AVG(heatsink_T) -1000) * 0.1 AS `Heatsink`,\r\n  (AVG(battery_T) -1000) * 0.1 AS `Battery`,\r\n  (AVG(DC_transformer_T) -1000) * 0.1 AS `DC Transformer`\r\nFROM\r\n  log.pv\r\nWHERE\r\n  $__timeFilter(timestamp)\r\nGROUP BY\r\n  `time`\r\nORDER BY\r\n  `time` DESC"
    }
   ]
  },
  {
   "title": "Dach",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT roof_V*0.1 AS `roof_V` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Carport",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT carport_V*0.1 AS `carport_V` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT\r\n\t`time`,\r\n\tCASE WHEN `inverter_p1_P` IS NULL THEN NULL WHEN `inverter_p1_P` < 0 THEN `inverter_p1_P` ELSE 0 END AS `inverter_p1_P_in`,\r\n\tCASE WHEN `inverter_p1_P` IS NULL THEN NULL WHEN `inverter_p1_P` > 0 THEN  `inverter_p1_P` ELSE 0 END AS `inverter_p1_P_out`,\r\n\tCASE WHEN `inverter_p2_P` IS NULL THEN NULL WHEN `inverter_p2_P` < 0 THEN `inverter_p2_P` ELSE 0 END AS `inverter_p2_P_in`,\r\n\tCASE WHEN `inverter_p2_P` IS NULL THEN NULL WHEN `inverter_p2_P` > 0 THEN  `inverter_p2_P` ELSE 0 END AS `inverter_p2_P_out`,\r\n\tCASE WHEN `inverter_p3_P` IS NULL THEN NULL WHEN `inverter_p3_P` < 0 THEN `inverter_p3_P` ELSE 0 END AS `inverter_p3_P_in`,\r\n\tCASE WHEN `inverter_p3_P` IS NULL THEN NULL WHEN `inverter_p3_P` > 0 THEN  `inverter_p3_P` ELSE 0 END AS `inverter_p3_P_out`,\r\n\tCASE WHEN `inverter_P` IS NULL THEN NULL WHEN `inverter_P` < 0 THEN -`inverter_P` ELSE 0 END AS `inverter_P_in`,\r\n\tCASE WHEN `inverter_P` IS NULL THEN NULL WHEN `inverter_P` > 0 THEN  `inverter_P` ELSE 0 END AS `inverter_P_out`\r\nFROM\r\n\t(SELECT\r\n\t  ROUND(ROUND(UNIX_TIMESTAMP(`timestamp`) * 1000 / $__interval_ms) * $__interval_ms) AS `time`,\r\n\t  AVG(`inverter_p1_P`) AS `inverter_p1_P`,\r\n\t  AVG(`inverter_p2_P`) AS `inverter_p2_P`,\r\n\t  AVG(`inverter_p3_P`) AS `inverter_p3_P`,\r\n\t  AVG(`inverter_P`) AS `inverter_P`\r\n\tFROM\r\n\t  log.pv\r\n\tWHERE\r\n\t  $__timeFilter(timestamp)\r\n\tGROUP BY\r\n\t\t`time`\r\n\tORDER BY\r\n\t  `time` DESC) AS `t`"
    }
   ]
  },
  {
   "title": "Phase 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_p1_P AS `inverter_p1_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Phase 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_p1_V*0.1 AS `inverter_p1_V` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Inverter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_frq*0.01 AS `inverter_frq` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Phase 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_p2_P AS `inverter_p2_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Phase 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_p2_V*0.1 AS `inverter_p2_V` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT load_frq*0.01 AS `load_frq` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT\r\n\t`time`,\r\n\t`inverter_p1_V`,\r\n\t`inverter_p2_V`,\r\n\t`inverter_p3_V`\r\nFROM\r\n\t(SELECT\r\n\t  ROUND(ROUND(UNIX_TIMESTAMP(`timestamp`) * 1000 / $__interval_ms) * $__interval_ms) AS `time`,\r\n\t  0.1*AVG(`inverter_p1_V`) AS `inverter_p1_V`,\r\n\t  0.1*AVG(`inverter_p2_V`) AS `inverter_p2_V`,\r\n\t  0.1*AVG(`inverter_p3_V`) AS `inverter_p3_V`\r\n\tFROM\r\n\t  log.pv\r\n\tWHERE\r\n\t  $__timeFilter(timestamp)\r\n\tGROUP BY\r\n\t\t`time`\r\n\tORDER BY\r\n\t  `time` DESC) AS `t`"
    }
   ]
  },
  {
   "title": "Phase 3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_p3_P AS `inverter_p3_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Phase 3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_p3_V*0.1 AS `inverter_p3_V` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Netz",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT grid_frq*0.01 AS `grid_frq` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT\r\n\t`time`,\r\n\t`inverter_frq`,\r\n\t`load_frq`,\r\n\t`grid_frq`\r\nFROM\r\n\t(SELECT\r\n\t  ROUND(ROUND(UNIX_TIMESTAMP(`timestamp`) * 1000 / $__interval_ms) * $__interval_ms) AS `time`,\r\n\t  0.01*AVG(`inverter_frq`) AS `inverter_frq`,\r\n\t  0.01*AVG(`load_frq`) AS `load_frq`,\r\n\t  0.01*AVG(`grid_frq`) AS `grid_frq`\r\n\tFROM\r\n\t  log.pv\r\n\tWHERE\r\n\t  $__timeFilter(timestamp)\r\n\tGROUP BY\r\n\t\t`time`\r\n\tORDER BY\r\n\t  `time` DESC) AS `t`"
    }
   ]
  },
  {
   "title": "Inverter AC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT inverter_P AS `inverter_P` FROM log.pv WHERE timestamp >= NOW() - INTERVAL 180 MINUTE  ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Uhrzeit Versatz",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "log",
     "rawSql": "SELECT UNIX_TIMESTAMP(NOW())-UNIX_TIMESTAMP(`inverter_timestamp`) AS `Offset` FROM log.pv_values LIMIT 1"
    }
   ]
  },
  { "title": "Historie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Energie / Tag",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    DATE(`date`) AS `date`,\r\n    `pv` * 0.1 AS `PV`,\r\n    `gen` * 0.1 AS `Generator`,\r\n    `grid_out` * 0.1 AS `Einspeisung`,\r\n    `grid_in` * 0.1 AS `Netzbezug`,\r\n    `battery_charge` * 0.1 AS `Akku laden`,\r\n    `battery_discharge` * 0.1 AS `Akku entladen`,\r\n    `load` * 0.1 AS `Verbrauch`\r\nFROM\r\n    `log`.`pv_E`\r\nWHERE\r\n    $__timeFilter(date)"
    }
   ]
  },
  {
   "title": "Energie / Monat",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    UNIX_TIMESTAMP(DATE(CONCAT(YEAR(`date`),'-',MONTH(`date`),'-01'))) AS `time`,\r\n    SUM(`pv`) * 0.1 AS `PV`,\r\n    SUM(`gen`) * 0.1 AS `Generator`,\r\n    SUM(`grid_out`) * 0.1 AS `Einspeisung`,\r\n    SUM(`grid_in`) * 0.1 AS `Netzbezug`,\r\n    SUM(`battery_charge`) * 0.1 AS `Akku laden`,\r\n    SUM(`battery_discharge`) * 0.1 AS `Akku entladen`,\r\n    SUM(`load`) * 0.1 AS `Verbrauch`\r\nFROM\r\n    `log`.`pv_E`\r\nWHERE\r\n    $__timeFilter(date)\r\nGROUP BY\r\n    `time`\r\n"
    }
   ]
  }
 ]
}